# Generated by Django 3.0.8 on 2020-08-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
